development:
  adapter: postgresql
  encoding: utf8
  database: random
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: random
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: ruby
  pool: 5
  username: postgres
  password: hongha1994

cucumber:
  <<: *TEST