# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dc92b4eb85a183f8ff946f2529a02a846752a181ae7f7feb42ca782c781631f84f712c5d285c65e6800d3c52e5ec251b7582a6d669618846e766bc706c126309

test:
  secret_key_base: b6c25f2225c881f414687fc0dae4563a901df06fef9109e44d02cd191a0d0cdac434c4515254768cd230187c58c29fdb65ba5e96281394b86e691968e3a9f8e4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
